kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: podman-kind
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 30000
    hostPort: 8000
networking:
  apiServerAddress: "127.0.0.1"
