"""Initial migration

Revision ID: 9152b24fc6d1
Revises:
Create Date: 2024-07-05 07:42:14.379474

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9152b24fc6d1"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "chat_messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(), nullable=True),
        sa.Column("message", sa.String(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chat_messages_id"), "chat_messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_chat_messages_message"), "chat_messages", ["message"], unique=False
    )
    op.create_index(
        op.f("ix_chat_messages_username"), "chat_messages", ["username"], unique=False
    )
    op.create_table(
        "websocket_connections",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("connection_id", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_websocket_connections_connection_id"),
        "websocket_connections",
        ["connection_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_websocket_connections_id"),
        "websocket_connections",
        ["id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_websocket_connections_id"), table_name="websocket_connections"
    )
    op.drop_index(
        op.f("ix_websocket_connections_connection_id"),
        table_name="websocket_connections",
    )
    op.drop_table("websocket_connections")
    op.drop_index(op.f("ix_chat_messages_username"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_message"), table_name="chat_messages")
    op.drop_index(op.f("ix_chat_messages_id"), table_name="chat_messages")
    op.drop_table("chat_messages")
    # ### end Alembic commands ###
